# Generated by Django 4.1.7 on 2023-03-12 18:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kanban', '0006_alter_category_name_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(default=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL),
        ),
    ]
