# Generated by Django 4.1.7 on 2023-03-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0007_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
