# Generated by Django 4.1.7 on 2023-03-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0010_alter_category_colour_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='prio',
        ),
    ]
