# Generated by Django 4.1.7 on 2023-03-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0015_task_test_alter_category_colour_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
    ]
