# Generated by Django 4.1.7 on 2023-03-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0021_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='initial',
            field=models.CharField(default='', max_length=3),
        ),
    ]
