# Generated by Django 4.1.7 on 2023-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0022_contact_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(default='', max_length=500),
        ),
    ]
