# Generated by Django 4.1.7 on 2023-03-16 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0027_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
