# Generated by Django 4.1.7 on 2023-03-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0029_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('u', 'urgent'), ('m', 'medium'), ('l', 'low')], default=('u', 'urgent'), max_length=7),
        ),
    ]
