# Generated by Django 4.1.7 on 2023-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0031_alter_task_assigned_to_alter_task_prio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, default=None, to='Kanban.contact'),
        ),
    ]
