# Generated by Django 4.1.7 on 2023-03-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0036_alter_task_specificid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='specificID',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
