# Generated by Django 4.1.7 on 2023-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0038_remove_task_created_date_remove_task_specificid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_Date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='specificID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
