# Generated by Django 4.1.7 on 2023-03-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0039_task_created_date_task_specificid_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='specificID',
            new_name='specificId',
        ),
    ]
