# Generated by Django 4.1.7 on 2023-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0040_rename_specificid_task_specificid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='toDo', max_length=30),
        ),
    ]
